name: formatMaps

on:
  pull_request:

permissions:
  contents: read

jobs:
  formatMaps:
    name: FormatMaps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupShinkrodb
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/shinkro/shinkrodb/releases/download/v0.2.5/shinkrodb_v0.2.5_linux_amd64.tar.gz"
          name: "shinkrodb"
          version: "0.2.5"

      - name: Check Format
        run: |
          shinkrodb format
