name: genMap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  gen-mal:
    name: GenerateMaps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: SetupShinkrodb
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/shinkro/shinkrodb/releases/download/v0.2.4/shinkrodb_v0.2.4_linux_amd64.tar.gz"
          name: "shinkrodb"
          version: "0.2.4"

      - name: GenerateMaps
        env:
          SHINKRODB_MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
          SHINKRODB_TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          shinkrodb genmap

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate maps
